INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Primary Workbooks','p2', '2022', 65, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Primary Workbooks','p2', '2022', 65, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Primary Workbooks','p2', '2022', 65, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Primary Workbooks','p2', '2022', 65, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Primary Workbooks','p2', '2022', 65, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Primary Workbooks','p2', '2022', 13, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Primary Workbooks','p3', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Primary Workbooks','p3', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Primary Workbooks','p3', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Primary Workbooks','p3', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Primary Workbooks','p3', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Primary Workbooks','p3', '2022', 13, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Writing Practice','p3', '2022', 5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Primary Workbooks','p4', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Primary Workbooks','p4', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Primary Workbooks','p4', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Primary Workbooks','p4', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Primary Workbooks','p4', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Primary Workbooks','p4', '2022', 13, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Writing Practice','p4', '2022', 5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Primary Workbooks','p5', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Primary Workbooks','p5', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Primary Workbooks','p5', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Primary Workbooks','p5', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Primary Workbooks','p5', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Primary Workbooks','p5', '2022', 13, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Writing Practice','p5', '2022', 5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Primary Workbooks','p6', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Primary Workbooks','p6', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Primary Workbooks','p6', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Primary Workbooks','p6', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Primary Workbooks','p6', '2022', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Primary Workbooks','p6', '2022', 13, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Writing Practice','p6', '2022', 5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Secondary Workbooks','s7', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Secondary Workbooks','s7', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Secondary Workbooks','s7', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Secondary Workbooks','s7', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Secondary Workbooks','s7', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('English Workbook','s7', '2022', 18.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Maths WB & HW','s7', '2022', 30.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Pearson Science','s7', '2022', 65.95, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Secondary Workbooks','s8', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Secondary Workbooks','s8', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Secondary Workbooks','s8', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Secondary Workbooks','s8', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Secondary Workbooks','s8', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('English Workbook','s8', '2022', 18.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Maths WB & HW','s8', '2022', 30.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Pearson Science','s8', '2022', 65.95, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Secondary Workbooks','s9', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Secondary Workbooks','s9', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Secondary Workbooks','s9', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Secondary Workbooks','s9', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Secondary Workbooks','s9', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('English Workbook','s9', '2022', 18.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Maths WB & HW','s9', '2022', 30.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Pearson Science','s9', '2022', 65.95, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] Secondary Workbooks','s10', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] Secondary Workbooks','s10', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] Secondary Workbooks','s10', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] Secondary Workbooks','s10', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] Secondary Workbooks','s10', '2022', 49, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('English Workbook','s10', '2022', 18.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Maths WB & HW','s10', '2022', 30.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Pearson Science','s10', '2022', 65.95, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] TT6 & FT6','tt6', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] TT6 & FT6','tt6', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] TT6 & FT6','tt6', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] TT6 & FT6','tt6', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] TT6 & FT6','tt6', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] TT6','tt6', '2022', 33, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] TT6','tt6', '2022', 33, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] TT6','tt6', '2022', 33, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] TT6','tt6', '2022', 33, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] TT6','tt6', '2022', 33, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] FT6 - English','tt6', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] FT6 - Mathmatics','tt6', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] FT6 - English','tt6', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] FT6 - Mathmatics','tt6', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] FT6 - English','tt6', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] FT6 - Mathmatics','tt6', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] FT6 - English','tt6', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] FT6 - Mathmatics','tt6', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] FT6 - English','tt6', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] FT6- Mathmatics','tt6', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('GA','tt6', '2022', 22.95, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] TT8 & FT8','tt8', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] TT8 & FT8','tt8', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] TT8 & FT8','tt8', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] TT8 & FT8','tt8', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] TT8 & FT8','tt8', '2022', 66, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] TT8','tt8', '2022', 33, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] TT8','tt8', '2022', 33, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] TT8','tt8', '2022', 33, 'SCI', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] TT8','tt8', '2022', 33, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] TT8','tt8', '2022', 33, 'ENG,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] FT8 - English','tt8', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] FT8 - Mathmatics','tt8', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] FT8 - English','tt8', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] FT8 - Mathmatics','tt8', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] FT8 - English','tt8', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] FT8 - Mathmatics','tt8', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] FT8 - English','tt8', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] FT8 - Mathmatics','tt8', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] FT8 - English','tt8', '2022', 16.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] FT8- Mathmatics','tt8', '2022', 16.5, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('Successful Comprehension','tt8', '2022', 31.95, 'MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] SRW','srw6', '2022', 14.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] SRW','srw6', '2022', 14.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] SRW','srw6', '2022', 14.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] SRW','srw6', '2022', 14.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] SRW','srw6', '2022', 14.5, 'ENG', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] SRW','srw8', '2022', 14.5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] SRW','srw8', '2022', 14.5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] SRW','srw8', '2022', 14.5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V4] SRW','srw8', '2022', 14.5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V5] SRW','srw8', '2022', 14.5, 'Writing', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V1] JMSS','jmss', '2022', 33, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V2] JMSS','jmss', '2022', 33, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('[V3] JMSS','jmss', '2022', 33, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseBook (name, grade, year, price, subjects, registerDate) VALUES ('VCE Book','vce', '2022', 1, 'ALL', CURDATE());
COMMIT;