INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','p2', 'vic', 'braybrook', 'Friday', 'Year 2 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('MON','p2', 'vic', 'braybrook', 'Monday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','p2', 'vic', 'braybrook', 'Saturday', 'Year 2 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','p2', 'vic', 'braybrook', 'Saturday', 'Year 2 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','p2', 'vic', 'braybrook', 'Thursday', 'Year 2 Thursday', CURDATE());

INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','p3', 'vic', 'braybrook', 'Friday', 'Year 3 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('MON','p3', 'vic', 'braybrook', 'Monday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','p3', 'vic', 'braybrook', 'Saturday', 'Year 3 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','p3', 'vic', 'braybrook', 'Saturday', 'Year 3 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','p3', 'vic', 'braybrook', 'Thursday', 'Year 3 Thursday', CURDATE());

INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','p4', 'vic', 'braybrook', 'Friday', 'Year 4 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('MON','p4', 'vic', 'braybrook', 'Monday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','p4', 'vic', 'braybrook', 'Saturday', 'Year 4 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','p4', 'vic', 'braybrook', 'Saturday', 'Year 4 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','p4', 'vic', 'braybrook', 'Thursday', 'Year 4 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','p4', 'vic', 'braybrook', 'Thursday', 'Year 4 Power Writing', CURDATE());

INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','p5', 'vic', 'braybrook', 'Friday', 'Year 5 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','p5', 'vic', 'braybrook', 'Tuesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','p5', 'vic', 'braybrook', 'Saturday', 'Year 5 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','p5', 'vic', 'braybrook', 'Saturday', 'Year 5 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','p5', 'vic', 'braybrook', 'Thursday', 'Year 5 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','p5', 'vic', 'braybrook', 'Tuesday', 'Year 5 Power Writing', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','p6', 'vic', 'braybrook', 'Friday', 'Year 6 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','p6', 'vic', 'braybrook', 'Tuesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','p6', 'vic', 'braybrook', 'Saturday', 'Year 6 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','p6', 'vic', 'braybrook', 'Saturday', 'Year 6 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','p6', 'vic', 'braybrook', 'Friday', 'Year 6 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','s7', 'vic', 'braybrook', 'Friday', 'Year 7 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','s7', 'vic', 'braybrook', 'Saturday', 'Year 7 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','s7', 'vic', 'braybrook', 'Saturday', 'Year 7 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','s7', 'vic', 'braybrook', 'Thursday', 'Year 7 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','s7', 'vic', 'braybrook', 'Tuesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','s8', 'vic', 'braybrook', 'Friday', 'Year 8 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','s8', 'vic', 'braybrook', 'Saturday', 'Year 8 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','s8', 'vic', 'braybrook', 'Saturday', 'Year 8 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','s8', 'vic', 'braybrook', 'Thursday', 'Year 8 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','s8', 'vic', 'braybrook', 'Wednesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','s9', 'vic', 'braybrook', 'Friday', 'Year 9 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','s9', 'vic', 'braybrook', 'Saturday', 'Year 9 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','s9', 'vic', 'braybrook', 'Saturday', 'Year 9 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','s9', 'vic', 'braybrook', 'Thursday', 'Year 9 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','s9', 'vic', 'braybrook', 'Wednesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','s10', 'vic', 'braybrook', 'Friday', 'Year 10 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','s10', 'vic', 'braybrook', 'Saturday', 'Year 10 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','s10', 'vic', 'braybrook', 'Saturday', 'Year 10 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','s10', 'vic', 'braybrook', 'Thursday', 'Year 10 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','s10', 'vic', 'braybrook', 'Wednesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','tt6', 'vic', 'braybrook', 'Friday', 'TT6 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','tt6', 'vic', 'braybrook', 'Saturday', 'TT6 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','tt6', 'vic', 'braybrook', 'Saturday', 'TT6 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','tt6', 'vic', 'braybrook', 'Thursday', 'TT6 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','tt6', 'vic', 'braybrook', 'Tuesday', 'Online Free Tutorial Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','tt6', 'vic', 'braybrook', 'Wednesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','tt6', 'vic', 'braybrook', 'Wednesday', 'PW6 Wednesday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI','tt8', 'vic', 'braybrook', 'Friday', 'TT8 Friday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM','tt8', 'vic', 'braybrook', 'Saturday', 'TT8 Saturday morning', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM','tt8', 'vic', 'braybrook', 'Saturday', 'TT8 Saturday afternoon', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('THU','tt8', 'vic', 'braybrook', 'Thursday', 'TT8 Thursday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE','tt8', 'vic', 'braybrook', 'Tuesday', 'Online Free Tutorial Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','tt8', 'vic', 'braybrook', 'Wednesday', 'Online Class', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED','tt8', 'vic', 'braybrook', 'Wednesday', 'PW8 Wednesday', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED W4','srw4', 'vic', 'braybrook', 'Wednesday', '[P4] SRW', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('TUE W5','srw5', 'vic', 'braybrook', 'Tuesday', '[P5] SRW', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED W6','srw6', 'vic', 'braybrook', 'Wednesday', '[TT6] SRW', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('WED W8','srw8', 'vic', 'braybrook', 'Wednesday', '[TT8] SRW', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI ENG 3&4','vce', 'vic', 'braybrook', 'Friday', 'VCE ENGLISH 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('FRI MM 3&4','vce', 'vic', 'braybrook', 'Friday', 'VCE ENGLISH 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM CHEM 1&2','vce', 'vic', 'braybrook', 'Saturday', 'VCE CHEMISTRY 1&2', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SAM CHEM 3&4','vce', 'vic', 'braybrook', 'Saturday', 'VCE CHEMISTRY 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM BIO 1&2','vce', 'vic', 'braybrook', 'Saturday', 'VCE BIOLOGY 1&2', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM BIO 3&4','vce', 'vic', 'braybrook', 'Saturday', 'VCE BIOLOGY 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM ENG 1&2','vce', 'vic', 'braybrook', 'Saturday', 'VCE ENGLISH 1&2', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM ENG 3&4','vce', 'vic', 'braybrook', 'Saturday', 'VCE ENGLISH 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM FM 3&4','vce', 'vic', 'braybrook', 'Saturday', 'VCE FURTHER MATHS 3&4', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM MM 1&2','vce', 'vic', 'braybrook', 'Saturday', 'VCE MATHS METHODS 1&2', CURDATE());
INSERT INTO jae.Course (name, grade, state, branch, day, description, registerDate) VALUES ('SPM MM 3&4','vce', 'vic', 'braybrook', 'Saturday', 'VCE MATHS METHODS 3&4', CURDATE());

COMMIT;
