-- P2
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (1, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (1, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (1, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (2, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (2, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (2, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (3, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (3, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (3, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (4, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (4, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (4, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (5, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (5, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (5, 3);
-- P3
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (6, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (6, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (6, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (7, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (7, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (7, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (8, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (8, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (8, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (9, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (9, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (9, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (10, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (10, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (10, 3);
-- P4
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (11, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (11, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (11, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (12, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (12, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (12, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (13, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (13, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (13, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (14, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (14, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (14, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (15, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (15, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (15, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (16, 1);
-- P5
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (17, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (17, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (17, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (18, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (18, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (18, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (19, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (19, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (19, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (20, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (20, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (20, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (21, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (21, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (21, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (22, 1);
-- P6
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (23, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (23, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (23, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (24, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (24, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (24, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (25, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (25, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (25, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (26, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (26, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (26, 3);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (27, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (27, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (27, 3);
-- S7
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (28, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (28, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (28, 5);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (29, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (29, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (29, 5);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (30, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (30, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (30, 5);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (31, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (31, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (31, 5);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (32, 1);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (32, 2);
INSERT INTO jae.Course_Subject (courseId, subjectId) VALUES (32, 5);
-- Requires more.....
COMMIT;


