INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P2] 3 Subjects','p2', '2022', 67, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P2] Online - 3 Subjects','p2', '2022', 46, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P2] 3 Subjects','p2', '2023', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P2] Online - 3 Subjects','p2', '2023', 49, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P3] 3 Subjects','p3', '2022', 67, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P3] Online - 3 Subjects','p3', '2022', 46, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P3] 3 Subjects','p3', '2023', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P3] Online - 3 Subjects','p3', '2023', 49, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P4] 3 Subjects','p4', '2022', 67, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P4] Online - 3 Subjects','p4', '2022', 46, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P4] 3 Subjects','p4', '2023', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P4] Online - 3 Subjects','p4', '2023', 49, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P5] 3 Subjects','p5', '2022', 67, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P5] Online - 3 Subjects','p5', '2022', 46, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P5] 3 Subjects','p5', '2023', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P5] Online - 3 Subjects','p5', '2023', 49, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P6] 3 Subjects','p6', '2022', 67, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P6] Online - 3 Subjects','p6', '2022', 46, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P6] 3 Subjects','p6', '2023', 70, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P6] Online - 3 Subjects','p6', '2023', 49, 'ENG,MA,GA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 3 Subjects','s7', '2022', 72, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 2 Subjects','s7', '2022', 62, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 1 Subject','s7', '2022', 47, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] Online - 3 Subjects','s7', '2022', 50, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 3 Subjects','s7', '2023', 75, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 2 Subjects','s7', '2023', 65, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] 1 Subject','s7', '2023', 50, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S7] Online - 3 Subjects','s7', '2023', 53, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 3 Subjects','s8', '2022', 72, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 2 Subjects','s8', '2022', 62, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 1 Subject','s8', '2022', 47, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] Online - 3 Subjects','s8', '2022', 50, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 3 Subjects','s8', '2023', 75, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 2 Subjects','s8', '2023', 65, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] 1 Subject','s8', '2023', 50, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S8] Online - 3 Subjects','s8', '2023', 53, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 3 Subjects','s9', '2022', 72, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 2 Subjects','s9', '2022', 62, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 1 Subject','s9', '2022', 47, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] Online - 3 Subjects','s9', '2022', 50, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 3 Subjects','s9', '2023', 75, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 2 Subjects','s9', '2023', 65, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] 1 Subject','s9', '2023', 50, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S9] Online - 3 Subjects','s9', '2023', 53, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 3 Subjects','s10', '2022', 72, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 2 Subjects','s10', '2022', 62, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 1 Subject','s10', '2022', 47, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] Online - 3 Subjects','s10', '2022', 50, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 3 Subjects','s10', '2023', 75, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 2 Subjects','s10', '2023', 65, 'Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] 1 Subject','s10', '2023', 50, 'One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10] Online - 3 Subjects','s10', '2023', 53, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[S10E] 3 Subjects','s10e', '2022', 72, 'ENG,MA,SCI', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] Course','tt6', '2022', 77, 'TT6 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] Online - TT6','tt6', '2022', 54, 'TT6 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] Course','tt6', '2023', 80, 'TT6 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] Online - TT6','tt6', '2023', 57, 'TT6 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] Course','tt8', '2022', 77, 'TT8 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] Online - TT8','tt8', '2022', 54, 'TT8 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] Course','tt8', '2023', 80, 'TT8 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] Online - TT8','tt8', '2023', 57, 'TT8 - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8E] Course Braybrook','tt8e', '2022', 50, 'TT8E - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8E] Course','tt8e', '2022', 80, 'TT8E - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8E] Online - TT8E','tt8e', '2022', 57, 'TT8E - ENG, MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P4] SRW','srw4', '2022', 49, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[P5] SRW','srw5', '2022', 49, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] S.R.W','srw6', '2022', 55, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT6] S.R.W','srw6', '2023', 58, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] S.R.W','srw8', '2022', 55, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[TT8] S.R.W','srw8', '2023', 58, 'Writing', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[JMSS] Course','jmss', '2022', 77, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[JMSS] Online - JMSS','jmss', '2022', 54, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[JMSS] Course','jmss', '2023', 80, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[JMSS] Online - JMSS','jmss', '2023', 57, 'SCI,MA', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 1 Sub','vce', '2022', 57, 'VCE - One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 2nd Sub','vce', '2022', 40, 'VCE - Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 3rd Sub','vce', '2022', 40, 'VCE - Three Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 1 Sub','vce', '2023', 60, 'VCE - One Subject', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 2nd Sub','vce', '2023', 40, 'VCE - Two Subjects', CURDATE());
INSERT INTO jae.CourseFee (name, grade, year, price, subjects, registerDate) VALUES ('[VCE] 3rd Sub','vce', '2023', 40, 'VCE - Three Subjects', CURDATE());
COMMIT;