INSERT INTO jae.course (grade, name, register_date) VALUES ('p2','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p2','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p3','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p3','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p4','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p4','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p5','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p5','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p6','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('p6','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s7','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s7','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s8','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s8','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s9','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s9','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s10','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s10','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s10e','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('s10e','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Class Test English',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Class Test Maths',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Extra Class Rcording',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','TT Free tutorial book',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','TT6 book',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Tuesday Extra Class',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt6','Written Expression',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Backup link',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Extra Class Rcording',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','TT Free tutorial book',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','TT8 book',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Tuesday Extra Class',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8','Written Expression',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Class Test English',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Class Test Maths',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Extra Class Rcording',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Tuesday Extra Class',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('tt8e','Written Expression',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('srw8','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('srw8','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('jmss','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('jmss','Recorded Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('jmss','Written Expression',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('jmss','JMSS book',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('vce','Online Weekly Lesson',sysdate());
INSERT INTO jae.course (grade, name, register_date) VALUES ('vce','Recorded Lesson',sysdate());
COMMIT;