INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p2','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p2','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p3','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p3','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p4','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p4','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p5','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p5','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p6','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('p6','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s7','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s7','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s8','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s8','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s9','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s9','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s10','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s10','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s10e','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('s10e','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Class Test English','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Class Test Maths','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Extra Class Rcording','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','TT Free tutorial book','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','TT6 book','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Tuesday Extra Class','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt6','Written Expression','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Backup link','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Extra Class Rcording','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','TT Free tutorial book','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','TT8 book','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Tuesday Extra Class','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8','Written Expression','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Class Test English','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Class Test Maths','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Extra Class Rcording','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Tuesday Extra Class','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('tt8e','Written Expression','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('srw8','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('srw8','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('jmss','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('jmss','Recorded Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('jmss','Written Expression','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('jmss','JMSS book','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('vce','Online Weekly Lesson','2022',sysdate());
INSERT INTO jae.Elearning (grade, name, year, registerDate) VALUES ('vce','Recorded Lesson','2022',sysdate());
COMMIT;